package com.example.prodqapi.documentAttachment;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Data Transfer Object for DocumentAttachment
 *
 * Used for API responses and client communication.
 * Contains document metadata without exposing internal entity details.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentAttachmentDTO {

    /**
     * Document ID
     */
    private Long id;

    /**
     * Parent order ID
     */
    private Long orderId;

    /**
     * Original filename (as uploaded by user)
     */
    private String fileName;

    /**
     * File size in bytes
     */
    private Long fileSize;

    /**
     * MIME type (e.g., application/pdf, image/jpeg)
     */
    private String fileType;

    /**
     * Document category
     */
    private DocumentCategory category;

    /**
     * Upload timestamp
     */
    private LocalDateTime uploadDate;

    /**
     * User ID who uploaded the document
     */
    private Long uploadedByUserId;

    /**
     * Display order for sorting (lower = higher priority)
     */
    private Integer displayOrder;

    /**
     * Download URL for this document (generated by backend)
     * Format: /api/order/documents/{id}/download
     */
    private String downloadUrl;

    /**
     * Helper method to generate download URL
     *
     * @param documentId Document ID
     * @return Download URL
     */
    public static String generateDownloadUrl(Long documentId) {
        return "/api/order/documents/" + documentId + "/download";
    }
}
