-- ============================================
-- Migration: Create document_attachment table
-- Purpose: Add support for multiple document attachments per order
-- Author: Generated by Claude Code
-- Date: 2025-12-01
-- ============================================

-- NOTE: Currently the project uses Hibernate with ddl-auto=create-drop,
-- so this table will be created automatically from the DocumentAttachment entity.
-- This migration script is provided for:
-- 1. Documentation purposes
-- 2. Future migration to Flyway/Liquibase
-- 3. Manual production deployments on MariaDB

-- Create document_attachment table
CREATE TABLE IF NOT EXISTS document_attachment (
    -- Primary key
    id BIGINT PRIMARY KEY AUTO_INCREMENT,

    -- Foreign key to Order table
    order_id INTEGER NOT NULL,

    -- File metadata
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    file_size BIGINT NOT NULL,
    file_type VARCHAR(100) NOT NULL,

    -- Document categorization
    category VARCHAR(50) NOT NULL,

    -- Upload metadata
    upload_date TIMESTAMP NOT NULL,
    uploaded_by_user_id BIGINT,

    -- Display ordering (for gallery sorting)
    display_order INT NOT NULL DEFAULT 0,

    -- Audit fields
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    -- Foreign key constraint
    CONSTRAINT fk_document_order FOREIGN KEY (order_id) REFERENCES _order(id) ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_document_order_id ON document_attachment(order_id);
CREATE INDEX IF NOT EXISTS idx_document_category ON document_attachment(category);
CREATE INDEX IF NOT EXISTS idx_document_upload_date ON document_attachment(upload_date);

-- ============================================
-- Verification queries (for testing)
-- ============================================

-- Check if table was created successfully
-- SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'document_attachment';

-- Check table structure
-- DESCRIBE document_attachment;

-- Check indexes
-- SHOW INDEX FROM document_attachment;

-- ============================================
-- Sample data for testing (optional)
-- ============================================

-- Insert sample document attachment (uncomment to use)
-- INSERT INTO document_attachment (
--     order_id,
--     file_name,
--     file_path,
--     file_size,
--     file_type,
--     category,
--     upload_date,
--     uploaded_by_user_id,
--     display_order,
--     created_at,
--     updated_at
-- ) VALUES (
--     1,                                              -- order_id (must exist in _order table)
--     'faktura_2024_01.pdf',                         -- file_name
--     'uploads/order-documents/1/uuid_faktura_2024_01.pdf', -- file_path
--     524288,                                        -- file_size (512KB)
--     'application/pdf',                             -- file_type
--     'INVOICE',                                     -- category
--     CURRENT_TIMESTAMP,                             -- upload_date
--     1,                                             -- uploaded_by_user_id
--     0,                                             -- display_order
--     CURRENT_TIMESTAMP,                             -- created_at
--     CURRENT_TIMESTAMP                              -- updated_at
-- );

-- ============================================
-- Rollback script (for emergencies)
-- ============================================

-- To rollback this migration, run:
-- DROP INDEX IF EXISTS idx_document_upload_date ON document_attachment;
-- DROP INDEX IF EXISTS idx_document_category ON document_attachment;
-- DROP INDEX IF EXISTS idx_document_order_id ON document_attachment;
-- DROP TABLE IF EXISTS document_attachment;
